const constants = {
  perm: {
    getEngineeringDepRequests: {
      id: 1,
      name: "getEngineeringDepRequests",
      type: "head",
      productId: 1,
      departmentId: 1,
    },
    getCallCenterDepRequests: {
      id: 2,
      name: "getCallCenterDepRequests",
      type: "head",
      productId: 1,
      departmentId: 2,
    },
    getSupportCommentsForStorekeeper: {
      id: 3,
      name: "getSupportCommentsForStorekeeper",
      type: "worker",
      productId: 1,
      departmentId: 5,
    },
    searchCustomer: {
      id: 4,
      name: "searchCustomer",
      type: "worker",
      productId: 1,
    },
    getCustomerRequests: {
      id: 5,
      name: "getCustomerRequests",
      type: "worker",
      productId: 1,
    },
    getCallCenterDepSupportRequests: {
      id: 6,
      name: "getCallCenterDepSupportRequests",
      type: "head",
      departmentId: 2,
      productId: 1,
    },
    assignNewSubRequests: {
      id: 7,
      name: "assignNewSubRequests",
      type: "head",
      productId: 1,
      departmentId: 1,
    },
    getStorekeeperReqById: {
      id: 8,
      name: "getStorekeeperReqById",
      productId: 1,
      departmentId: 5,
      type: "worker",
    },
    configSupportRequest: {
      id: 9,
      name: "configSupportRequest",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getEngHeadSupportRequests: {
      id: 10,
      name: "getEngHeadSupportRequests",
      type: "head",
      departmentId: 1,
      productId: 1,
    },
    unConfigSupportRequest: {
      id: 11,
      name: "unConfigSupportRequest",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getEngineeringDepSupportRequests: {
      id: 12,
      name: "getEngineeringDepSupportRequests",
      type: "head",
      departmentId: 1,
      productId: 1,
    },
    assignSupportRequests: {
      id: 13,
      name: "assignSupportRequests",
      type: "head",
      productId: 1,
      departmentId: 1,
    },
    finalCheckSupRequest: {
      id: 14,
      name: "finalCheckSupRequest",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    finalUnCheckSupRequest: {
      id: 15,
      name: "finalUnCheckSupRequest",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    configNewSubRequest: {
      id: 16,
      name: "configNewSubRequest",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    unConfigNewSubRequest: {
      id: 17,
      name: "unConfigNewSubRequest",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    finalCheckNewSubRequest: {
      id: 18,
      name: "finalCheckNewSubRequest",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    finalUnCheckNewSubRequest: {
      id: 19,
      name: "finalUnCheckNewSubRequest",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    addSignatureToNewSubReq: {
      id: 20,
      name: "addSignatureToNewSubReq",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    addContractIdToNewSubReq: {
      id: 21,
      name: "addContractIdToNewSubReq",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getEngineerRequests: {
      id: 22,
      name: "getEngineerRequests",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getConfigWorkerRequests: {
      id: 23,
      name: "getConfigWorkerRequests",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    getCallCenterRequests: {
      id: 24,
      name: "getCallCenterRequests",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    getRequestById: {
      id: 25,
      name: "getRequestById",
      type: "worker",
      productId: 1,
    },
    addWorker: {
      id: 26,
      name: "addWorker",
      type: "worker",
      productId: 1,
    },
    getWorkerById: {
      id: 27,
      name: "getWorkerById",
      type: "worker",
      productId: 1,
    },
    attachPermAndGroup: {
      id: 28,
      name: "attachPermAndGroup",
      type: "worker",
      productId: 1,
    },
    editRequestType: {
      id: 29,
      name: "editRequestType",
      type: "worker",
      productId: 1,
    },
    pushNewSubRequest: {
      id: 30,
      name: "pushNewSubRequest",
      type: "worker",
      productId: 1,
    },
    editNewSubRequest: {
      id: 31,
      name: "editNewSubRequest",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    deleteNewSubRequest: {
      id: 32,
      name: "deleteNewSubRequest",
      type: "head",
      productId: 1,
    },
    deleteSupportRequest: {
      id: 33,
      name: "deleteSupportRequest",
      type: "head",
      productId: 1,
    },
    getCallCenterSupportRequests: {
      id: 34,
      name: "getCallCenterSupportRequests",
      type: "worker",
      departmentId: 2,
      productId: 1,
    },
    getNewSubRecMaterials: {
      id: 35,
      name: "getNewSubRecMaterials",
      type: "worker",
      productId: 1,
    },
    deleteNewSubRecMaterial: {
      id: 36,
      name: "deleteNewSubRecMaterial",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    editNewSubRecMaterial: {
      id: 37,
      name: "editNewSubRecMaterial",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    addNewSubRecMaterial: {
      id: 38,
      name: "addNewSubRecMaterial",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getNewSubUsedMaterials: {
      id: 39,
      name: "getNewSubUsedMaterials",
      type: "worker",
      productId: 1,
    },
    deleteNewSubUsedMaterial: {
      id: 40,
      name: "deleteNewSubUsedMaterial",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    editNewSubUsedMaterial: {
      id: 41,
      name: "editNewSubUsedMaterial",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    addNewSubUsedMaterial: {
      id: 42,
      name: "addNewSubUsedMaterial",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getSupportRecMaterials: {
      id: 43,
      name: "getSupportRecMaterials",
      type: "worker",
      productId: 1,
    },
    deleteSupportRecMaterial: {
      id: 44,
      name: "deleteSupportRecMaterial",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    editSupportRecMaterial: {
      id: 45,
      name: "editSupportRecMaterial",
      productId: 1,
      departmentId: 1,
      type: "worker",
    },
    addSupportRecMaterial: {
      id: 46,
      name: "addSupportRecMaterial",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getSupportUsedMaterials: {
      id: 47,
      name: "getSupportUsedMaterials",
      type: "worker",
      productId: 1,
    },
    deleteSupportUsedMaterial: {
      id: 48,
      name: "deleteSupportUsedMaterial",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    editSupportUsedMaterial: {
      id: 49,
      name: "editSupportUsedMaterial",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    addSupportUsedMaterial: {
      id: 50,
      name: "addSupportUsedMaterial",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    addNewSubComment: {
      id: 51,
      name: "addNewSubComment",
      type: "worker",
      productId: 1,
    },
    getNewSubComments: {
      id: 52,
      name: "getNewSubComments",
      type: "worker",
      productId: 1,
    },
    addSupportComment: {
      id: 53,
      name: "addSupportComment",
      type: "worker",
      productId: 1,
    },
    getSupportComments: {
      id: 54,
      name: "getSupportComments",
      type: "worker",
      productId: 1,
    },
    getMaterialById: {
      id: 55,
      name: "getMaterialById",
      type: "worker",
      productId: 1,
    },
    editMaterial: {
      id: 56,
      name: "editMaterial",
      type: "worker",
      productId: 1,
    },
    disableMaterial: {
      id: 57,
      name: "disableMaterial",
      type: "worker",
      productId: 1,
    },
    addMaterial: {
      id: 58,
      name: "addMaterial",
      type: "worker",
      productId: 1,
    },
    getMaterials: {
      id: 59,
      name: "getMaterials",
      type: "worker",
      productId: 1,
    },
    editCustomer: {
      id: 60,
      name: "editCustomer",
      type: "worker",
      productId: 1,
    },
    getCustomerById: {
      id: 61,
      name: "getCustomerById",
      type: "worker",
      productId: 1,
    },
    getCustomers: {
      id: 62,
      name: "getCustomers",
      type: "worker",
      productId: 1,
    },
    connectCustomer: {
      id: 63,
      name: "connectCustomer",
      type: "worker",
      productId: 1,
    },
    checkCustomerAddress: {
      id: 64,
      name: "checkCustomerAddress",
      type: "worker",
      productId: 1,
    },
    getDepartments: {
      id: 65,
      name: "getDepartments",
      type: "worker",
      productId: 1,
    },
    addDepartment: {
      id: 66,
      name: "addDepartment",
      type: "worker",
      productId: 1,
    },
    deleteDepartment: {
      id: 67,
      name: "deleteDepartment",
      type: "worker",
      productId: 1,
    },
    recoverDepartment: {
      id: 68,
      name: "recoverDepartment",
      type: "worker",
      productId: 1,
    },
    editDepartment: {
      id: 69,
      name: "editDepartment",
      type: "worker",
      productId: 1,
    },
    getDepartmentById: {
      id: 70,
      name: "getDepartmentById",
      type: "worker",
      productId: 1,
    },
    getEngineers: {
      id: 71,
      name: "getEngineers",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getWorkers: {
      id: 72,
      name: "getWorkers",
      type: "worker",
      productId: 1,
    },
    createNewSubRequest: {
      id: 73,
      name: "createNewSubRequest",
      type: "worker",
      productId: 1,
    },
    getTempNewSubRequests: {
      id: 74,
      name: "createNewSubRequest",
      type: "worker",
      productId: 1,
    },
    rejectTempNewSubRequest: {
      id: 75,
      name: "rejectTempNewSubRequest",
      type: "worker",
      productId: 1,
    },
    getWaitingTempNewSubRequests: {
      id: 76,
      name: "getWaitingTempNewSubRequests",
      type: "worker",
      productId: 1,
    },
    getCallCenterHeadReqById: {
      id: 77,
      name: "getCallCenterHeadReqById",
      type: "head",
      productId: 1,
      departmentId: 2,
    },
    getEngineeringHeadReqById: {
      id: 78,
      name: "getEngineeringHeadReqById",
      type: "head",
      productId: 1,
      departmentId: 1,
    },
    getConfigWorkerReqById: {
      id: 79,
      name: "getConfigWorkerReqById",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getEngineerReqById: {
      id: 80,
      name: "getEngineerReqById",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getCallCenterReqById: {
      id: 81,
      name: "getCallCenterReqById",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    getNewSubRecMatForEng: {
      id: 82,
      name: "getNewSubRecMatForEng",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getNewSubRecMatForConf: {
      id: 83,
      name: "getNewSubRecMatForConf",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getNewSubRecMatForCall: {
      id: 84,
      name: "getNewSubRecMatForCall",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    getNewSubRecMatForEngHead: {
      id: 85,
      name: "getNewSubRecMatForEngHead",
      type: "head",
      productId: 1,
      departmentId: 1,
    },
    getNewSubRecMatForCallHead: {
      id: 86,
      name: "getNewSubRecMatForCallHead",
      type: "head",
      productId: 1,
      departmentId: 2,
    },
    getNewSubUsedMatForEng: {
      id: 87,
      name: "getNewSubUsedMatForEng",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getNewSubUsedMatForConf: {
      id: 88,
      name: "getNewSubUsedMatForConf",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getNewSubUsedMatForCall: {
      id: 89,
      name: "getNewSubUsedMatForCall",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    getNewSubUsedMatForEngHead: {
      id: 90,
      name: "getNewSubUsedMatForEngHead",
      type: "head",
      productId: 1,
      departmentId: 1,
    },
    getNewSubUsedMatForCallHead: {
      id: 91,
      name: "getNewSubUsedMatForCallHead",
      type: "head",
      productId: 1,
      departmentId: 2,
    },
    getNewSubCommentsForEng: {
      id: 92,
      name: "getNewSubCommentsForEng",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getNewSubCommentsForConf: {
      id: 93,
      name: "getNewSubCommentsForConf",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getNewSubCommentsForCall: {
      id: 94,
      name: "getNewSubCommentsForCall",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    getNewSubCommentsForEngHead: {
      id: 95,
      name: "getNewSubCommentsForEngHead",
      type: "head",
      productId: 1,
      departmentId: 1,
    },
    getNewSubCommentsForCallHead: {
      id: 96,
      name: "getNewSubCommentsForCallHead",
      type: "head",
      productId: 1,
      departmentId: 2,
    },
    getSupportCommentsForEng: {
      id: 97,
      name: "getSupportCommentsForEng",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getSupportCommentsForConf: {
      id: 98,
      name: "getSupportCommentsForConf",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getSupportCommentsForCall: {
      id: 99,
      name: "getSupportCommentsForCall",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    getSupportCommentsForEngHead: {
      id: 100,
      name: "getSupportCommentsForEngHead",
      type: "head",
      productId: 1,
      departmentId: 1,
    },
    getSupportCommentsForCallHead: {
      id: 101,
      name: "getSupportCommentsForCallHead",
      type: "head",
      productId: 1,
      departmentId: 2,
    },
    getSupportRecMatForEng: {
      id: 102,
      name: "getSupportRecMatForEng",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getSupportRecMatForConf: {
      id: 103,
      name: "getSupportRecMatForConf",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getSupportRecMatForCall: {
      id: 104,
      name: "getSupportRecMatForCall",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    getSupportRecMatForEngHead: {
      id: 105,
      name: "getSupportRecMatForEngHead",
      type: "head",
      productId: 1,
      departmentId: 1,
    },
    getSupportRecMatForCallHead: {
      id: 106,
      name: "getSupportRecMatForCallHead",
      type: "head",
      productId: 1,
      departmentId: 2,
    },
    getSupportUsedMatForEng: {
      id: 107,
      name: "getSupportUsedMatForEng",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getSupportUsedMatForConf: {
      id: 108,
      name: "getSupportUsedMatForConf",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    getSupportUsedMatForCall: {
      id: 109,
      name: "getSupportUsedMatForCall",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    getSupportUsedMatForEngHead: {
      id: 110,
      name: "getSupportUsedMatForEngHead",
      type: "head",
      productId: 1,
      departmentId: 1,
    },
    getSupportUsedMatForCallHead: {
      id: 111,
      name: "getSupportUsedMatForCallHead",
      type: "head",
      productId: 1,
      departmentId: 2,
    },
    getTempNewSubReqById: {
      id: 112,
      name: "getTempNewSubReqById",
      type: "worker",
      productId: 1,
      departmentId: null,
    },
    searchWorkers: {
      id: 113,
      name: "searchWorkers",
      type: "worker",
      productId: 1,
      departmentId: null,
    },
    getWorkersByDep: {
      id: 114,
      name: "getWorkersByDep",
      type: "worker",
      productId: 1,
      departmentId: null,
    },
    changeWorkersDep: {
      id: 115,
      name: "changeWorkersDep",
      type: "worker",
      productId: 1,
      departmentId: null,
    },
    makePermissionsGroup: {
      id: 116,
      name: "makePermissionsGroup",
      type: "worker",
      productId: 1,
      departmentId: null,
    },
    editPermissionsGroup: {
      id: 117,
      name: "editPermissionsGroup",
      type: "worker",
      productId: 1,
      departmentId: null,
    },
    getPermissions: {
      id: 118,
      name: "getPermissions",
      type: "worker",
      productId: 1,
      departmentId: null,
    },
    getPermissionGroups: {
      id: 119,
      name: "getPermissionGroups",
      type: "worker",
      productId: 1,
      departmentId: null,
    },
    deletePermissionsGroups: {
      id: 120,
      name: "deletePermissionsGroups",
      type: "worker",
      productId: 1,
      departmentId: null,
    },
    getPermsGroupById: {
      id: 121,
      name: "getPermsGroupById",
      type: "worker",
      productId: 1,
      departmentId: null,
    },
    getWorkerPermsAndGroups: {
      id: 122,
      name: "getWorkerPermsAndGroups",
      type: "worker",
      productId: 1,
      departmentId: null,
    },
    newSubscriberOperatorReport: {
      id: 123,
      name: "newSubscriberOperatorReport",
      type: "worker",
      productId: 1,
      departmentId: null,
    },
    newSubscriberCancel: {
      id: 124,
      name: "newSubscriberCancel",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    newSubscriberCancelRequest: {
      id: 125,
      name: "newSubscriberCancelRequest",
      type: "worker",
      productId: 1,
      departmentId: null,
    },
    newSubscriberRevert: {
      id: 126,
      name: "newSubscriberRevert",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    newSubscriberCancelRequestForEng: {
      id: 127,
      name: "newSubscriberCancelRequestForEng",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    editNewSubRequestForEng: {
      id: 128,
      name: "editNewSubRequestForEng",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    editNewSubRequestForEngHead: {
      id: 129,
      name: "editNewSubRequestForEngHead",
      type: "head",
      productId: 1,
      departmentId: 1,
    },
    pushNewSubRequestForEng: {
      id: 130,
      name: "pushNewSubRequestForEng",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    pushNewSubRequestForEngHead: {
      id: 131,
      name: "pushNewSubRequestForEngHead",
      type: "head",
      productId: 1,
      departmentId: 1,
    },
    getSupportRecMatForStorekeeper: {
      id: 132,
      name: "getSupportRecMatForStorekeeper",
      type: "worker",
      productId: 1,
      departmentId: 5,
    },
    getSupportUsedMatForStorekeeper: {
      id: 133,
      name: "getSupportUsedMatForStorekeeper",
      type: "worker",
      productId: 1,
      departmentId: 5,
    },
    newSubscriberCancelRequestForEngHead: {
      id: 134,
      name: "newSubscriberCancelRequestForEngHead",
      type: "head",
      productId: 1,
      departmentId: 1,
    },
    getAddresses: {
      id: 135,
      name: "getAddresses",
      type: "worker",
      productId: 1,
      departmentId: null,
    },
    addAddress: {
      id: 136,
      name: "addAddress",
      type: "worker",
      productId: 1,
      departmentId: null,
    },
    editAddress: {
      id: 137,
      name: "editAddress",
      type: "worker",
      productId: 1,
      departmentId: null,
    },
    getEngHeadRequests: {
      id: 138,
      name: "getEngHeadRequests",
      type: "head",
      departmentId: 1,
      productId: 1,
    },
    createChangeAddressRequest: {
      id: 139,
      name: "createChangeAddressRequest",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    pushChangeAddressRequest: {
      id: 140,
      name: "pushChangeAddressRequest",
      type: "worker",
      productId: 1,
      departmentId: 1,
    },
    pushBackChangeAddressRequest: {
      id: 141,
      name: "pushBackChangeAddressRequest",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    closeChangeAddressRequest: {
      id: 142,
      name: "closeChangeAddressRequest",
      type: "worker",
      productId: 1,
      departmentId: 2,
    },
    createSupRejectReq: {
      id: 143,
      name: "createSupRejectReq",
      type: "worker",
      departmentId: 2,
      productId: 1,
    },
    pushSupRejectReqToCallCenter: {
      id: 144,
      name: "pushSupRejectReqToCallCenter",
      type: "worker",
      departmentId: 1,
      productId: 1,
    },
    pushSupRejectReqToStorekeeper: {
      id: 145,
      name: "pushSupRejectReqToStorekeeper",
      type: "worker",
      departmentId: 1,
      productId: 1,
    },
    pushSupRejectReqToConfig: {
      id: 146,
      name: "pushSupRejectReqToConfig",
      type: "worker",
      departmentId: 5,
      productId: 1,
    },
    closeSupRejectReq: {
      id: 147,
      name: "closeSupRejectReq",
      type: "worker",
      departmentId: 2,
      productId: 1,
    },
    getEngineerSupportRequests: {
      id: 148,
      name: "getEngineerSupportRequests",
      type: "worker",
      departmentId: 1,
      productId: 1,
    },
    getConfigWorkerSupportRequests: {
      id: 149,
      name: "getConfigWorkerSupportRequests",
      type: "worker",
      departmentId: 1,
      productId: 1,
    },
    getStoreKeeperSupportRequests: {
      id: 150,
      name: "getStorekeeperSupportRequests",
      type: "worker",
      departmentId: 5,
      productId: 1,
    },
    getFinanceLawDepSupportRequests: {
      id: 151,
      name: "getFinanceLawDepSupportRequests",
      type: "head",
      departmentId: 5,
      productId: 1,
    },
  },
  group: {
    engineer: {
      id: 1,
      name: "engineer",
      type: "worker",
      departmentId: 1,
      productId: 1,
    },
    configWorker: {
      id: 2,
      name: "configWorker",
      type: "worker",
      departmentId: 1,
      productId: 1,
    },
    callCenter: {
      id: 3,
      name: "callCenter",
      type: "worker",
      departmentId: 2,
      productId: 1,
    },
    engineeringHead: {
      id: 4,
      name: "engineeringHead",
      type: "head",
      departmentId: 1,
      productId: 1,
    },
    callCenterHead: {
      id: 5,
      name: "callCenterHead",
      type: "head",
      departmentId: 2,
      productId: 1,
    },
    RequestOwner: {
      id: 6,
      type: "owner",
      name: "RequestOwner",
      productId: 1,
    },
    receptionForCallCenter: {
      id: 7,
      name: "receptionForCallCenter",
      type: "worker",
      departmentId: 3,
      productId: 1,
    },
    hrHead: {
      id: 8,
      name: "hrHead",
      type: "head",
      departmentId: 4,
      productId: 1,
    },
    hr: {
      id: 9,
      name: "hr",
      type: "worker",
      departmentId: 4,
      productId: 1,
    },
    storekeeper: {
      id: 10,
      name: "storekeeper",
      type: "worker",
      departmentId: 5,
      productId: 1,
    },
  },
};

export default constants;
